### PR TITLE
Avoid database access loading metadata

### LINKED ISSUE #553: [Timestampable] Unnecessary database access
Hi,

In [TimestampableSubscriber](https://github.com/KnpLabs/DoctrineBehaviors/blob/a076c4a4794d05aeaac81ec9ae18009d1696a939/src/EventSubscriber/TimestampableSubscriber.php#L63) a call to database connection is done to choose between `datetimetz` and `datetime` metadata format to add.
It throws an exception if you install your vendors before starting the database (or if you don't need a started database in the CI for example). Maybe it would be better to set the format in the configuration with a defaut value?

If it's ok for you, I will create the corresponding PR.

### PR DESCRIPTION
**Pull request by pmontoya**
To fix #553
Move datetime type field from database type detection to service configuration

### CODE REVIEW

File: tests/ORM/TimestampableMakeEntityTest.php [hunk 1]
```diff
@@ -29,9 +29,4 @@ public function testMakeEntityEmptyEvent(): void
         $doctrineEventManager->dispatchEvent(Events::loadClassMetadata, $eventArgs);
         $this->expectNotToPerformAssertions();
     }
-
-    protected function provideCustomConfig(): ?string
```
Comment (pmontoya) [inline tests/ORM/TimestampableMakeEntityTest.php:33]: I think it's no more necessary. What do you think?

**Comment by TomasVotruba** [comment]
Looks good!

**Comment by TomasVotruba** [comment]
Thank you
